title: Srinivas's Homepage
description: My personal webpage
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
remote_theme: "jeffreytse/jekyll-theme-yat"
# Add the following to activate the plugin
plugins:
  - jekyll-remote-theme
